# Generated by Django 4.0.3 on 2023-10-11 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='post', serialize=False, to='posts.posts', unique=True)),
                ('content', models.TextField(max_length=100)),
                ('large_content', models.TextField()),
            ],
            options={
                'db_table': 'post_content',
            },
        ),
    ]
