# Generated by Django 4.0.3 on 2023-10-11 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_alter_users_table'),
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='posts',
            name='comment_count',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='posts',
            name='deleted',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.OneToOneField(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='posts.posts'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='sign.users'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user_id',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='sign.users'),
        ),
    ]
