# Generated by Django 4.0.3 on 2023-10-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_content_options_posts_comment_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={},
        ),
    ]
