# Generated by Django 4.0.3 on 2023-10-11 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_comment_post_id_alter_comment_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.OneToOneField(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='posts.posts'),
        ),
        migrations.AlterField(
            model_name='content',
            name='post_id',
            field=models.OneToOneField(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='post', serialize=False, to='posts.posts'),
        ),
    ]
