# Generated by Django 4.0.3 on 2023-10-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_comment_post_id_alter_content_post_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
