# Generated by Django 4.0.3 on 2023-10-11 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_alter_users_table'),
        ('posts', '0008_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.SmallIntegerField()),
                ('post_id', models.OneToOneField(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='posts.posts')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='sign.users')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
