version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./db_data:/var/lib/mysql
      - ./mysql:/etc/mysql/conf.d
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db
      MYSQL_USER: semo
      MYSQL_PASSWORD: 1234
    restart: always

  app:
    depends_on:
      - db
    image: suhun/django
    volumes:
      - ./app_data:/var/www/html
    command: bash -c "python manage.py makemigrations &&
                  python manage.py migrate && 
                  gunicorn --workers=3 --bind 0.0.0.0:8000 --preload config.wsgi:application"
    ports:
      - '8000:8000'
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3307
      MYSQL_DATABASE: db
      MYSQL_USER: semo
      MYSQL_PASSWORD: 1234
    restart: always

  nginx:
    image: nginx
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./__collect_static:/data/static
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app
#
#  certbot:
#    image: certbot/certbot
#    restart: unless-stopped
#    volumes:
#      - ./data/certbot/conf:/etc/letsencrypt
#      - ./data/certbot/www:/var/www/certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"





