version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: db
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db
      MYSQL_USER: semo
      MYSQL_PASSWORD: 1234
    restart: always

  app:
    depends_on:
      - db
    image: suhun/django
    volumes:
      - ./app_data:/var/www/html
    command: bash -c "python manage.py makemigrations &&
                  python manage.py migrate && 
                  python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3307
      MYSQL_DATABASE: db
      MYSQL_USER: semo
      MYSQL_PASSWORD: 1234






