version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db
      MYSQL_USER: semo
      MYSQL_PASSWORD: 1234
    restart: always

  app:
    depends_on:
      - db
    image: suhun/django:0.1.3
    volumes:
      - ./app_data:/var/www/html
    command: bash -c "python manage.py makemigrations &&
                  python manage.py migrate && 
                  gunicorn --bind 0:8000 config.wsgi:application"
    ports:
      - '8000:8000'
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3307
      MYSQL_DATABASE: db
      MYSQL_USER: semo
      MYSQL_PASSWORD: 1234

  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d






