# Generated by Django 4.0.3 on 2023-10-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_alter_users_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
